Repository Polly-Contrib/Simmy, pull requests merged in 2019-12, with the labels that each got.

#55 Namespace, filename and property-name cleanups
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourTResultAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourTResultWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Latency/InjectLatencyAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Latency/InjectLatencyTResultAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Latency/InjectLatencyTResultWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Latency/InjectLatencyWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Outcomes/InjectFaultAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Outcomes/InjectFaultTResultAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Outcomes/InjectFaultTResultWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Outcomes/InjectFaultWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy/Behavior/AsyncInjectBehaviourOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Behavior/AsyncInjectBehaviourPolicy.cs
  src/Polly.Contrib.Simmy/Behavior/AsyncInjectBehaviourTResultOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Behavior/InjectBehaviourAsyncOptions.cs
  src/Polly.Contrib.Simmy/Behavior/InjectBehaviourAsyncOptionsExtensions.cs
  src/Polly.Contrib.Simmy/Behavior/InjectBehaviourOptions.cs
  src/Polly.Contrib.Simmy/Behavior/InjectBehaviourOptionsExtensions.cs
  src/Polly.Contrib.Simmy/Behavior/InjectBehaviourOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Behavior/InjectBehaviourPolicy.cs
  src/Polly.Contrib.Simmy/Behavior/InjectBehaviourTResultOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Latency/AsyncInjectLatencyOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Latency/AsyncInjectLatencyPolicy.cs
  src/Polly.Contrib.Simmy/Latency/InjectLatencyAsyncOptions.cs
  src/Polly.Contrib.Simmy/Latency/InjectLatencyAsyncOptionsExtensions.cs
  src/Polly.Contrib.Simmy/Latency/InjectLatencyOptions.cs
  src/Polly.Contrib.Simmy/Latency/InjectLatencyOptionsExtensions.cs
  src/Polly.Contrib.Simmy/Latency/InjectLatencyOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Latency/InjectLatencyPolicy.cs
  src/Polly.Contrib.Simmy/Outcomes/AsyncInjectOutcomeOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Outcomes/AsyncInjectOutcomePolicy.cs
  src/Polly.Contrib.Simmy/Outcomes/AsyncInjectOutcomeSyntax.cs
  src/Polly.Contrib.Simmy/Outcomes/InjectOutcomeAsyncOptions.cs
  src/Polly.Contrib.Simmy/Outcomes/InjectOutcomeAsyncOptionsExtensions.cs
  src/Polly.Contrib.Simmy/Outcomes/InjectOutcomeOptions.cs
  src/Polly.Contrib.Simmy/Outcomes/InjectOutcomeOptionsExtensions.cs
  src/Polly.Contrib.Simmy/Outcomes/InjectOutcomeOptionsSyntax.cs
  src/Polly.Contrib.Simmy/Outcomes/InjectOutcomePolicy.cs
  src/Polly.Contrib.Simmy/Outcomes/InjectOutcomeSyntax.cs
Labels: new API

#51 Add .NET Standard 2.1 target
  appveyor.yml
  build.cake
  build.ps1
  src/Polly.Contrib.Simmy.Specs/Polly.Contrib.Simmy.Specs.csproj
  src/Polly.Contrib.Simmy.nuspec
  src/Polly.Contrib.Simmy/Polly.Contrib.Simmy.csproj
Labels: enhancement, target frameworks

#57 Fixes unit tests execution on .Net Core 3.0
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourTResultAsyncWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourTResultWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy.Specs/Behavior/InjectBehaviourWithOptionsSpecs.cs
  src/Polly.Contrib.Simmy/MonkeyEngine.cs
Labels: bug

#58 New syntax documentation
  README.md
Labels: documentation

#59 Split definition-and-example code block
  README.md
Labels: documentation
